version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
before_build:
- cmd: git submodule update --init --recursive & cmake -G "Visual Studio 15 2017 Win64"
build:
  project: PACKAGE.vcxproj
  verbosity: minimal